[package]
name = "dbmon"
version = "0.1.0"
authors = ["jesskfulwood <jesskfulwood@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
fig = { path = "../../" }
wasm-bindgen = "0.2.48"
rand = "0.7.0"
xorshift = "0.1.3"
rand_xorshift = "0.2.0"
