[package]
name = "demo"
version = "0.1.0"
authors = ["jesskfulwood <jesskfulwood@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
fig = { path = "../../" }
wasm-bindgen = "0.2.37"
rand = { version = "0.6.5", features = ["wasm-bindgen"] }
